spring.application.name=Task_manager

# ===============================
# DATASOURCE - Oracle Cloud
#spring.datasource.url=jdbc:oracle:thin:@iscloud_tp?TNS_ADMIN=C:/walletIscloud
spring.datasource.url=jdbc:oracle:thin:@iscloud_tp
spring.datasource.username=WKSP_TASKMAN
spring.datasource.password=Ciaociao89$$

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect