spring.application.name=Task_manager

# ===============================
# DATASOURCE - Oracle Cloud
#spring.datasource.url=jdbc:oracle:thin:@iscloud_tp?TNS_ADMIN=C:/walletIscloud
##spring.datasource.url=jdbc:oracle:thin:@iscloud_tp
#spring.datasource.username=WKSP_TASKMAN
#spring.datasource.password=Ciaociao89$$
#
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.datasource.url=jdbc:postgresql://postgres:5432/taskdb
spring.datasource.username=user
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=create

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=



spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=target/schema.sql
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.main.web-application-type=none
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.validation-timeout=10000

# Disabilita Liquibase
spring.liquibase.enabled=false