CREATE SCHEMA IF NOT EXISTS wksp_taskman;

create table wksp_taskman.anagrafica (
                                         genere varchar(1),
                                         ind_canc boolean default false,
                                         nascita date,
                                         id_anagrafica bigint generated by default as identity,
                                         cf varchar(16),
                                         cognome varchar(150) not null,
                                         nome varchar(150) not null,
                                         primary key (id_anagrafica),
                                         constraint UNQ_ANAGRAFICA_CF unique (cf)
);

create table wksp_taskman.attivita (
                                       fine date,
                                       ind_canc boolean default false,
                                       inizio date not null,
                                       mod_date date default CURRENT_DATE not null,
                                       id_attivita bigint not null,
                                       operatore_id bigint,
                                       priorita_id bigint,
                                       progetto_id bigint,
                                       stato_id bigint,
                                       tipo_id bigint,
                                       nome varchar(250),
                                       descrizione varchar(4000),
                                       primary key (id_attivita)
);

create table wksp_taskman.categorie_mime (
                                             id_categoria_mime bigint not null,
                                             etichetta varchar(20) not null,
                                             primary key (id_categoria_mime),
                                             constraint UNQ_CATEGORIE_MIME_ETICHETTA unique (etichetta)
);

create table wksp_taskman.cellulare_persona (
                                                ind_canc boolean default false,
                                                mod_date date default CURRENT_DATE not null,
                                                id_recapito bigint not null,
                                                persona_id bigint not null,
                                                tipo_id bigint not null,
                                                numero varchar(20),
                                                primary key (id_recapito)
);

create table wksp_taskman.dipendenti (
                                         data_assunzione date not null,
                                         data_cessazione date not null,
                                         livello_inquadramento boolean,
                                         ID_DIPENDENTE bigint not null,
                                         ditta_id bigint,
                                         reparto_id bigint not null,
                                         responsabile_id bigint,
                                         matricola varchar(10) not null,
                                         mansione varchar(40),
                                         tipo_contratto varchar(100),
                                         email_aziendale varchar(180) not null,
                                         primary key (data_assunzione, ID_DIPENDENTE),
                                         constraint PK_DIPENDENTI_MATRICOLA unique (matricola),
                                         constraint UNQ_DIPENDENTI_EMAIL unique (email_aziendale)
);

create table wksp_taskman.ditte (
                                    data_costituzione date,
                                    ind_canc boolean default false,
                                    mod_date date default CURRENT_DATE not null,
                                    id_ditta bigint not null,
                                    logo_mime_id bigint,
                                    tipo_ditta_id bigint,
                                    p_iva varchar(11),
                                    cod_fiscale varchar(16),
                                    ragione_sociale varchar(320) not null,
                                    descrizione varchar(4000),
                                    logo bytea,
                                    primary key (id_ditta),
                                    constraint UNQ_DITTE_PIVA unique (p_iva)
);

create table wksp_taskman.email_persona (
                                            ind_canc boolean default false,
                                            is_pec boolean,
                                            is_scaduta boolean,
                                            mod_date date default CURRENT_DATE not null,
                                            id_recapito bigint not null,
                                            persona_id bigint not null,
                                            tipo_id bigint not null,
                                            email varchar(180) not null,
                                            primary key (id_recapito),
                                            constraint UNQ_EMAIL_PERSONA_EMAIL unique (email)
);

create table wksp_taskman.esecuzione (
                                         "data" date,
                                         durata numeric(5,2),
                                         ind_canc boolean default false,
                                         mod_date date default CURRENT_DATE not null,
                                         attivita_id bigint not null,
                                         id_esecuzione bigint not null,
                                         operatore_id bigint not null,
                                         note varchar(4000),
                                         primary key (id_esecuzione)
);

create table wksp_taskman.indirizzi_persona (
                                                ind_canc boolean default false,
                                                mod_date date default CURRENT_DATE not null,
                                                cap varchar(5),
                                                id_recapito bigint not null,
                                                persona_id bigint not null,
                                                tipo_id bigint not null,
                                                cod_comune varchar(20),
                                                telefono varchar(20),
                                                indirizzo varchar(150),
                                                primary key (id_recapito)
);

create table wksp_taskman.locali (
                                     ind_canc boolean default false,
                                     mod_date date default CURRENT_DATE,
                                     id_locale bigint not null,
                                     sede_id bigint,
                                     tipo_locale_id bigint,
                                     nome varchar(70),
                                     mappa bytea,
                                     primary key (id_locale)
);

create table wksp_taskman.postazioni (
                                         ind_canc boolean default false,
                                         mod_date date default CURRENT_DATE not null,
                                         id_postazione bigint not null,
                                         locali_id bigint,
                                         codice varchar(10),
                                         primary key (id_postazione)
);

create table wksp_taskman.priorita (
                                       is_inattiva boolean,
                                       id_priorita bigint not null,
                                       ordine bigint,
                                       color varchar(30) default 'u-color-14-bg' not null,
                                       etichetta varchar(30),
                                       icona varchar(30),
                                       primary key (id_priorita),
                                       constraint UNQ_PRIORITA_ORDINE unique (ordine)
);

create table wksp_taskman.progetti (
                                       fine date,
                                       ind_canc boolean default false,
                                       inizio date not null,
                                       mod_date date default CURRENT_DATE,
                                       id_progetto bigint generated by default as identity,
                                       responsabile_id bigint,
                                       nome varchar(250) not null,
                                       descrizione varchar(4000),
                                       primary key (id_progetto)
);

create table wksp_taskman.progetto_x_anagrafica (
                                                    has_att_aggiungi boolean,
                                                    has_att_assegna boolean,
                                                    has_att_prendi boolean,
                                                    has_att_stato boolean,
                                                    has_prg_gestisci boolean,
                                                    PERSONA_ID bigint not null,
                                                    PROGETTO_ID bigint not null,
                                                    ruolo_id bigint,
                                                    primary key (PERSONA_ID, PROGETTO_ID)
);

create table wksp_taskman.reparti (
                                      ind_canc boolean default false,
                                      mod_date date default CURRENT_DATE not null,
                                      ditta_id bigint not null,
                                      id_reparto bigint not null,
                                      responsabile_id bigint,
                                      nome varchar(80) not null,
                                      primary key (id_reparto)
);

create table wksp_taskman.ruoli_progetto (
                                             id_ruolo bigint not null,
                                             ind_canc boolean default false,
                                             etichetta varchar(70) not null,
                                             icona varchar(150),
                                             descrizione varchar(4000),
                                             primary key (id_ruolo)
);

create table wksp_taskman.ruoli_utente (
                                           id_ruolo bigint not null,
                                           nome_ruolo varchar(50) not null unique,
                                           descrizione varchar(255),
                                           primary key (id_ruolo)
);

create table wksp_taskman.sedi (
                                   ind_canc boolean default false,
                                   is_esterna boolean,
                                   localita_id varchar(4),
                                   mod_date date default CURRENT_DATE not null,
                                   cap varchar(5),
                                   ditta_id bigint,
                                   id_sede bigint not null,
                                   tipo_sede_id bigint,
                                   indirizzo varchar(110),
                                   denominazione varchar(150),
                                   primary key (id_sede)
);

create table wksp_taskman.stati_attivita (
                                             is_inattiva boolean,
                                             id_stato_attivita bigint not null,
                                             ordine bigint,
                                             etichetta varchar(30),
                                             icona varchar(150),
                                             primary key (id_stato_attivita),
                                             constraint UNQ_STATI_ORDINE unique (ordine)
);

create table wksp_taskman.stati_utente (
                                           id_stato bigint not null,
                                           etichetta varchar(20) not null,
                                           descrizione varchar(4000),
                                           primary key (id_stato),
                                           constraint UNQ_STATI_UTENTE_ETICHETTA unique (etichetta)
);

create table wksp_taskman.tipi_attivita (
                                            ind_canc boolean default false,
                                            id_tipo_attivita bigint not null,
                                            etichetta varchar(30) not null,
                                            icona varchar(30),
                                            primary key (id_tipo_attivita)
);

create table wksp_taskman.tipi_cellulare (
                                             ind_canc boolean default false,
                                             id_tipo_cellulare bigint not null,
                                             rilevanza bigint,
                                             etichetta varchar(30) not null,
                                             primary key (id_tipo_cellulare),
                                             constraint UNQ_TIPI_CELLULARE_ETICHETTA unique (etichetta),
                                             constraint UNQ_TIPI_CELLULARE_RILEVANZA unique (rilevanza)
);

create table wksp_taskman.tipi_ditta (
                                         ind_canc boolean default false,
                                         id_tipo_ditta bigint not null,
                                         codice varchar(10) not null,
                                         sigla varchar(10),
                                         descrizione varchar(100) not null,
                                         primary key (id_tipo_ditta),
                                         constraint UNQ_TM_TIPI_DITTA_CODICE unique (codice)
);

create table wksp_taskman.tipi_email (
                                         ind_canc boolean default false,
                                         id_tipo_email bigint not null,
                                         rilevanza bigint,
                                         etichetta varchar(30) not null,
                                         primary key (id_tipo_email),
                                         constraint UNQ_TM_TIPI_EMAIL_ETICHETTA unique (etichetta),
                                         constraint UNQ_TIPI_EMAIL_RILEVANZA unique (rilevanza)
);

create table wksp_taskman.tipi_indirizzo (
                                             ind_canc boolean default false,
                                             id_tipo_indirizzo bigint not null,
                                             rilevanza bigint,
                                             etichetta varchar(30) not null,
                                             primary key (id_tipo_indirizzo),
                                             constraint UNQ_TIPI_INDIRIZZO_ETICHETTA unique (etichetta),
                                             constraint UNQ_TIPI_INDIRIZZO_RILEVANZA unique (rilevanza)
);

create table wksp_taskman.tipi_locale (
                                          ind_canc boolean default false,
                                          id_tipo_locale bigint not null,
                                          etichetta varchar(30),
                                          primary key (id_tipo_locale),
                                          constraint UNQ_TIPI_LOCALE_ETICHETTA unique (etichetta)
);

create table wksp_taskman.tipi_mime (
                                        extension varchar(5),
                                        categoria_id bigint not null,
                                        id_mime bigint not null,
                                        etichetta varchar(50) not null,
                                        mime varchar(100) not null,
                                        primary key (id_mime),
                                        constraint UNQ_TIPI_MIME_ETICHETTA unique (etichetta),
                                        constraint UNQ_TIPI_MIME_MIME unique (mime)
);

create table wksp_taskman.tipi_sede (
                                        ind_canc boolean default false,
                                        id_tipo_sede bigint not null,
                                        rilevanza bigint,
                                        etichetta varchar(30),
                                        primary key (id_tipo_sede),
                                        constraint UNQ_TIPI_SEDE_ETICHETTA unique (etichetta),
                                        constraint UNQ_TIPI_SEDE_RILEVANZA unique (rilevanza)
);

create table wksp_taskman.utenti (
                                     data_scadenza_pwd date not null,
                                     forza_cambio_pwd boolean default false,
                                     id_utente bigint not null,
                                     ruolo_id bigint not null,
                                     stato_utente_id bigint,
                                     tentativi_falliti bigint,
                                     codice_attivazione varchar(16),
                                     password varchar(100) not null,
                                     userid varchar(100) not null,
                                     primary key (id_utente),
                                     constraint UNQ_UTENTI_USERID unique (userid)
);

create sequence ruoli_seq start with 1 increment by 1;



alter table if exists wksp_taskman.attivita
       add constraint FKnev4pwuu0msfy71a01psdcsro
       foreign key (operatore_id)
       references wksp_taskman.anagrafica
       on delete set null;

alter table if exists wksp_taskman.attivita
       add constraint FK7hm5dobovohfoulcuevm3ng2l
       foreign key (priorita_id)
       references wksp_taskman.priorita
       on delete restrict;

alter table if exists wksp_taskman.attivita
       add constraint FKchx4xntrbu90tjrubb8jww7nk
       foreign key (progetto_id)
       references wksp_taskman.progetti
       on delete cascade;

alter table if exists wksp_taskman.attivita
       add constraint FK8xu83nxxkymc5xd3x81ioj3n7
       foreign key (stato_id)
       references wksp_taskman.stati_attivita
       on delete restrict;

alter table if exists wksp_taskman.attivita
       add constraint FKh4ol2y0iwp6any7ooixf0bsnb
       foreign key (tipo_id)
       references wksp_taskman.tipi_attivita
       on delete restrict;

alter table if exists wksp_taskman.cellulare_persona
       add constraint FK68y2y1v04n5er6wnfwdb5ru4w
       foreign key (persona_id)
       references wksp_taskman.anagrafica
       on delete cascade;

alter table if exists wksp_taskman.cellulare_persona
       add constraint FKptaxv1khuy2arotg6ou7yo3ik
       foreign key (tipo_id)
       references wksp_taskman.tipi_cellulare
       on delete restrict;

alter table if exists wksp_taskman.dipendenti
       add constraint FKbwnf57buhwsjw7aj01wjdrx6s
       foreign key (ditta_id)
       references wksp_taskman.ditte
       on delete restrict;

alter table if exists wksp_taskman.dipendenti
       add constraint FKhquhdgsrmwpp9yfdt4af5siek
       foreign key (id_dipendente)
       references wksp_taskman.anagrafica
       on delete cascade;

alter table if exists wksp_taskman.dipendenti
       add constraint FKgo7oix8ky07lca5t0kt181c2c
       foreign key (reparto_id)
       references wksp_taskman.reparti
       on delete set null;

alter table if exists wksp_taskman.dipendenti
       add constraint FKi7p2xfkcfsry4n91r21qw3wqf
       foreign key (responsabile_id)
       references wksp_taskman.anagrafica
       on delete set null;

alter table if exists wksp_taskman.ditte
       add constraint FKfk3tupku2rs7iofrw3k3nkivb
       foreign key (logo_mime_id)
       references wksp_taskman.tipi_mime
       on delete restrict;

alter table if exists wksp_taskman.email_persona
       add constraint FK1tugkfe84dbe0f88mkg3j19i3
       foreign key (persona_id)
       references wksp_taskman.anagrafica
       on delete restrict;

alter table if exists wksp_taskman.email_persona
       add constraint FK1kb2l57glfe0dfliq7w409h0m
       foreign key (tipo_id)
       references wksp_taskman.tipi_email
       on delete restrict;

alter table if exists wksp_taskman.esecuzione
       add constraint FKltflpcvmi4g7xrayhik487jc4
       foreign key (attivita_id)
       references wksp_taskman.attivita
       on delete restrict;

alter table if exists wksp_taskman.esecuzione
       add constraint FKldpg1h927io2kv1cdner80p5a
       foreign key (operatore_id)
       references wksp_taskman.anagrafica
       on delete restrict;

alter table if exists wksp_taskman.indirizzi_persona
       add constraint FK7t17f33mjfyiqs6f4bbpcnyho
       foreign key (persona_id)
       references wksp_taskman.anagrafica
       on delete cascade;

alter table if exists wksp_taskman.indirizzi_persona
       add constraint FKgb9yjlj7aoru80lryq7rv8lka
       foreign key (tipo_id)
       references wksp_taskman.tipi_indirizzo
       on delete restrict;

alter table if exists wksp_taskman.locali
       add constraint FK5l5b9mgsbty3bveto4e60gn8
       foreign key (sede_id)
       references wksp_taskman.sedi
       on delete cascade;

alter table if exists wksp_taskman.locali
       add constraint FKf4bji0lds4k737wrh3e9w9kca
       foreign key (tipo_locale_id)
       references wksp_taskman.tipi_locale
       on delete restrict;

alter table if exists wksp_taskman.postazioni
       add constraint FKtc22fviv094wi1bkamvkd3pkw
       foreign key (locali_id)
       references wksp_taskman.locali
       on delete restrict;

alter table if exists wksp_taskman.progetti
       add constraint FKfoiafb41fykg251onyww6waeq
       foreign key (responsabile_id)
       references wksp_taskman.anagrafica
       on delete restrict;

alter table if exists wksp_taskman.progetto_x_anagrafica
       add constraint FKilrkxm31pecs98kaxof4vhwky
       foreign key (persona_id)
       references wksp_taskman.anagrafica
       on delete cascade;

alter table if exists wksp_taskman.progetto_x_anagrafica
       add constraint FKorcny5r8oyinmdlq8mhgclpj7
       foreign key (progetto_id)
       references wksp_taskman.progetti
       on delete cascade;

alter table if exists wksp_taskman.progetto_x_anagrafica
       add constraint FK5evsttxk283xnxk1d29ryb3e4
       foreign key (ruolo_id)
       references wksp_taskman.ruoli_progetto
       on delete restrict;

alter table if exists wksp_taskman.reparti
       add constraint FKlvm6v1invps9wdblr4lcl1y0s
       foreign key (ditta_id)
       references wksp_taskman.ditte
       on delete cascade;

alter table if exists wksp_taskman.reparti
       add constraint FKtsjihrqa5paq2kegp6gwfmed
       foreign key (responsabile_id)
       references wksp_taskman.anagrafica
       on delete set null;

alter table if exists wksp_taskman.sedi
       add constraint FKglgk1nnue3h47tcfaf3evh081
       foreign key (ditta_id)
       references wksp_taskman.ditte
       on delete cascade;

alter table if exists wksp_taskman.sedi
       add constraint FK6ub5kjv2nyopq15l0aqkitot9
       foreign key (tipo_sede_id)
       references wksp_taskman.tipi_sede
       on delete restrict;

alter table if exists wksp_taskman.tipi_mime
       add constraint FKsth6h1sc5qsm4bh8rabumxjar
       foreign key (categoria_id)
       references wksp_taskman.categorie_mime
       on delete restrict;

alter table if exists wksp_taskman.utenti
       add constraint FKhw6gm1q7osfsu993olw20u4y5
       foreign key (ruolo_id)
       references wksp_taskman.ruoli_utente;

alter table if exists wksp_taskman.utenti
       add constraint FKmchd9sxeu0y5k25dpmsqayoy
       foreign key (stato_utente_id)
       references wksp_taskman.stati_utente
       on delete restrict;

alter table if exists wksp_taskman.utenti
       add constraint FK1wct3dtcfxf3leuje8e5qrj1k
       foreign key (id_utente)
       references wksp_taskman.anagrafica
       on delete restrict;
